// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a balanced Chilean menu for a specified number of days.
 *
 * - generateMenu - A function that generates the menu.
 * - GenerateMenuInput - The input type for the generateMenu function.
 * - GenerateMenuOutput - The return type for the generateMenu function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMenuInputSchema = z.object({
  numberOfDays: z
    .number()
    .describe('The number of days for which to generate the menu.')
    .min(1),
});
export type GenerateMenuInput = z.infer<typeof GenerateMenuInputSchema>;

const MenuItemSchema = z.object({
  day: z.number().describe('The day number in the menu.'),
  meal: z.string().describe('The name of the meal (breakfast, lunch, dinner).'),
  recipeName: z.string().describe('The name of the recipe for this meal.'),
  ingredients: z.array(z.string()).describe('List of ingredients for the recipe.'),
  instructions: z.string().describe('Instructions to prepare the recipe.'),
});

const GenerateMenuOutputSchema = z.object({
  menu: z.array(MenuItemSchema).describe('The generated menu for the specified number of days.'),
  shoppingList: z.array(z.string()).describe('A unified shopping list for all recipes in the menu.'),
});
export type GenerateMenuOutput = z.infer<typeof GenerateMenuOutputSchema>;

export async function generateMenu(input: GenerateMenuInput): Promise<GenerateMenuOutput> {
  return generateMenuFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMenuPrompt',
  input: {schema: GenerateMenuInputSchema},
  output: {schema: GenerateMenuOutputSchema},
  prompt: `You are a Chilean chef specializing in creating balanced and delicious menus.

You will generate a menu for {{numberOfDays}} days, with recipes suitable for 4 people. The menu should consist of breakfast, lunch, and dinner. All meals should be based on chilean gastronomy.

After generating the menu, you will create a unified shopping list based on the ingredients required for all the recipes. The shopping list will contain ingredients commonly sold in chilean markets.

Return the menu and shopping list in JSON format.

Example Menu Item:
{
  "day": 1,
  "meal": "Breakfast",
  "recipeName": "Pan con Palta",
  "ingredients": ["Pan", "Palta", "Sal"],
  "instructions": "Untar la palta en el pan y agregar sal a gusto."
}

Example Shopping List:
["Pan", "Palta", "Sal", ...]

`,
});

const generateMenuFlow = ai.defineFlow(
  {
    name: 'generateMenuFlow',
    inputSchema: GenerateMenuInputSchema,
    outputSchema: GenerateMenuOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
