
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a Chilean menu with suggested and optional lunches for a specified number of days and people,
 * including Peruvian and Latin American dishes popular in Chile.
 *
 * - generateMenu - A function that generates the menu.
 * - GenerateMenuInput - The input type for the generateMenu function.
 * - GenerateMenuOutput - The return type for the generateMenu function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMenuInputSchema = z.object({
  numberOfDays: z
    .number()
    .describe('El número de días para los cuales generar el menú.')
    .min(1),
  numberOfPeople: z
    .number()
    .describe('El número de personas para las cuales generar cada receta del menú.')
    .min(1)
    .max(16)
    .default(4),
});
export type GenerateMenuInput = z.infer<typeof GenerateMenuInputSchema>;

const CoreRecipeSchema = z.object({
  recipeName: z.string().describe('Nombre de la receta.'),
  ingredients: z.array(z.string()).describe('Lista de ingredientes para la receta, con cantidades para el número de personas especificado (ej: "Arroz: 2 tazas", "Carne Molida: 500g").'),
  instructions: z.string().describe('Instrucciones para preparar la receta.'),
  evocativeDescription: z.string().describe('Un texto corto, poético/evocador para incitar a cocinar el plato.'),
  imageDataUri: z.string().optional().describe('URI de datos de la imagen generada para el plato (opcional).'),
});
export type CoreRecipe = z.infer<typeof CoreRecipeSchema>;

const DailyMenuSchema = z.object({
  day: z.number().describe('El número del día en el menú.'),
  suggestedLunch: CoreRecipeSchema.describe('El almuerzo sugerido para este día.'),
  optionalLunch: CoreRecipeSchema.describe('El almuerzo opcional para este día.'),
});
export type DailyMenu = z.infer<typeof DailyMenuSchema>;

const GenerateMenuOutputSchema = z.object({
  menu: z.array(DailyMenuSchema).describe('El menú generado con almuerzos sugeridos y opcionales para cada día.'),
});
export type GenerateMenuOutput = z.infer<typeof GenerateMenuOutputSchema>;

export async function generateMenu(input: GenerateMenuInput): Promise<GenerateMenuOutput> {
  return generateMenuFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMenuPrompt',
  input: {schema: GenerateMenuInputSchema},
  output: {schema: GenerateMenuOutputSchema},
  config: {
    temperature: 0.9, // Aumenta la creatividad y variedad
  },
  prompt: `Eres un chef experto y CREATIVO. Tu misión es diseñar menús que sean balanceados, deliciosos y, fundamentalmente, MUY VARIADOS Y POCO REPETITIVOS.
Sorpréndeme con tu conocimiento profundo de la gastronomía chilena, peruana y una amplia gama de joyas culinarias latinoamericanas, incluyendo platos caseros y tesoros menos conocidos pero igualmente exquisitos que se disfrutan en Chile.
Para asegurar la variedad, incluye diferentes tipos de proteínas (vacuno, cerdo, pollo, pescado, mariscos, legumbres, huevos), diversos métodos de cocción (guisos, horneados, salteados, a la parrilla, al vapor), y considera platos de distintas regiones de Chile y de otros países latinoamericanos que sean populares o que podrían serlo.
Evita sugerir platos que sean demasiado similares entre sí en días consecutivos o dentro de la misma semana.

Generarás un menú para {{numberOfDays}} días. Cada receta del menú debe ser para {{numberOfPeople}} personas.

Para cada receta (tanto sugerida como opcional), incluye:
- recipeName: Nombre de la receta.
- ingredients: Lista de ingredientes. Para cada ingrediente, especifica la cantidad necesaria para {{numberOfPeople}} personas de la forma más precisa posible (e.g., 'Arroz: 2 tazas', 'Carne Molida: 500g', 'Cebolla: 1 grande'). No uses guiones '-' al inicio de cada ingrediente, solo la cadena de texto con el ingrediente y su cantidad.
- instructions: Instrucciones detalladas de preparación.
- evocativeDescription: Un texto corto (1-2 frases), inspirador y "semi-poético" que invite a preparar y disfrutar el plato. Ejemplo: "Un clásico reconfortante que abraza el alma con cada bocado." o "Sabores vibrantes que te transportarán a una tarde soleada junto al mar."

No incluyas desayunos ni cenas, solo las dos opciones de almuerzo por día.
No incluyas el campo imageDataUri en tu respuesta JSON, se generará por separado.

Devuelve el menú en formato JSON.

Ejemplo de cómo debería ser la estructura para un día (este ejemplo es si {{numberOfPeople}} fuera 4, debes ajustar las cantidades para el valor de {{numberOfPeople}} que se te provea):
{
  "day": 1,
  "suggestedLunch": {
    "recipeName": "Pastel de Choclo",
    "ingredients": ["Carne Molida: 500g", "Pollo: 1 pechuga", "Cebolla: 1 unidad", "Choclo: 5 tazas", "Leche: 1 taza", "Albahaca: a gusto", "Huevo Duro: 2 unidades", "Aceitunas: 8 unidades"],
    "instructions": "Preparar un pino con carne molida, pollo y cebolla. Aparte, moler choclo con leche y albahaca. En una fuente para horno, colocar el pino, huevo duro y aceitunas. Cubrir con la mezcla de choclo. Hornear hasta dorar.",
    "evocativeDescription": "Un abrazo de la tierra chilena, donde el dulzor del choclo se encuentra con el sabor profundo del pino."
  },
  "optionalLunch": {
    "recipeName": "Lentejas con Arroz",
    "ingredients": ["Lentejas: 2 tazas", "Arroz: 2 tazas", "Cebolla: 1 unidad", "Zanahoria: 2 unidades", "Zapallo: 200g", "Longaniza (opcional): 2 unidades"],
    "instructions": "Remojar las lentejas. Cocinarlas con cebolla, zanahoria y zapallo picados. Agregar longaniza si se desea. Servir con arroz graneado.",
    "evocativeDescription": "Un plato humilde y poderoso, perfecto para recargar energías con el sabor de casa."
  }
}

Asegúrate de que la salida sea solo el objeto JSON que se ajusta al esquema de salida. Las cantidades de los ingredientes deben ser calculadas con precisión para {{numberOfPeople}} personas. Si {{numberOfPeople}} es 1, asegúrate de que las cantidades sean para una sola persona.
`,
});

const generateMenuFlow = ai.defineFlow(
  {
    name: 'generateMenuFlow',
    inputSchema: GenerateMenuInputSchema,
    outputSchema: GenerateMenuOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

